  # Site settings
title: jarbouvic
description: "Victor Moreau"
url: "https://www.jarbouvic.fr"

# Author
author:
  name: Victor Moreau
  url: www.jarbouvic.fr
  email: jarbouvic@gmail.com

# Build settings
markdown: kramdown

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-relative-links
  - jekyll-wikirefs
  - jekyll-include-cache

# Permalinks
permalink: /:categories/:year-:month-:day/:title

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"