  # Site settings
title: jarbouvic
description: "Victor Moreau"
url: "https://www.jarbouvic.fr"

# Author
author:
  name: Victor Moreau
  url: www.jarbouvic.fr
  email: jarbouvic@gmail.com

# Build settings
markdown: kramdown

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-relative-links
  - jekyll-include-cache
  - jekyll-wikirefs

# Permalinks
permalink: /:year-:month-:day/:title

collections:
  collections:
    output: true

defaults:
  -
    scope:
      path: ""
      type: "posts" 
    values:
      layout: "posts"
  -
    scope:
      path: ""
      type: "collections" 
    values:
      layout: "posts"