# Site settings
title: jarbouvic
description: "Victor Moreau"
url: "https://www.jarbouvic.fr"

# Author
author:
  name: Victor Moreau
  url: www.jarbouvic.fr
  email: jarbouvic@gmail.com

# Build settings
markdown: kramdown
include:
  - _pages
  - _collections

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-include-cache
  - jekyll-relative-links
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink: /:year-:month-:day/:title
paginate: 5

collections:
  collections:
    output: true

defaults:
  -
    scope:
      path: ""
      type: "collections" # a collection in your site, in plural form
    values:
      layout: "post"