# Site settings
title: jarbouvic
description: "Victor Moreau"
url: "https://jarbouvic.github.io"

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name: Victor Moreau
  url: jarbouvic.github.io
  email: jarbouvic@gmail.com

# Build settings
markdown: kramdown
include:
  - _pages

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-wikirefs
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink: /:year-:month-:day/:title
paginate: 5

collections:
  books:
    output: true