# Site settings
title: jarbouvic
description: "Victor Moreau"
url: "https://jarbouvic.github.io"

# Author
author:
  name: Victor Moreau
  url: jarbouvic.github.io
  email: jarbouvic@gmail.com

# Build settings
markdown: kramdown
include:
  - _pages

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-include-cache
  - jekyll-relative-links
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink: /:year-:month-:day/:title
paginate: 5

collections:
  read:
    output: true
  watched:
    output: true
  done:
    output: true

defaults:
  -
    scope:
      path: ""
      type: "read" # a collection in your site, in plural form
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "watched" # a collection in your site, in plural form
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "done" # a collection in your site, in plural form
    values:
      layout: "post"