# Site settings
title: "jarbouvic"
description: > 
Victor Moreau

author: Victor Moreau
email: jarbouvic@gmail.com
github_username: jarbouvic

baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://jarbouvic.github.io" # the base hostname & protocol for your site

google_analytics_id: UA-1111111111-1
disqus_id:

# Build settings
include: [_pages]
markdown: kramdown
permalink: /:year/:month/:title.html

sass:
    style: compressed

exclude: [vendor]
